repositories:
 - name: opensearch
   url: https://opensearch-project.github.io/helm-charts/

releases:
- name: opensearch
  namespace: opensearch
  chart: opensearch/opensearch
  version: "2"
  set:
    - name: persistence.enabled
      value: true
    - name: persistence.storageClass
      value: sata
    - name: persistence.accessModes
      values:
        - ReadWriteOnce
    - name: persistence.size
      value: 10Gi

- name: opensearch-dashboards
  namespace: opensearch
  chart: opensearch/opensearch-dashboards
  version: "2"
