repositories:
 - name: minio
   url: https://charts.bitnami.com/bitnami

TBD

releases:
  - name: minio
    namespace: minio
    chart: minio/minio
    version: "17"
    set:
      - name: persistence.enabled
        value: true
      - name: persistence.storageClass
        value: sata
      - name: persistence.accessModes
        value:
          - ReadWriteOnce
      - name: persistence.size
        value: 10Gi
