// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/";
  };
  "routes/resume.tsx": {
    id: "resume";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "resume": typeof import("./src/routes/resume.tsx");
};