{{- $sp := .Values.secretProvider -}}
{{- if eq $sp "onepasswordSDK" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.onePassword.accessTokenSecretName }}
type: Opaque
data:
  {{ .Values.onePassword.accessTokenSecretKey }}: {{ .Values.onePassword.secret | b64enc }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.name }}
spec:
  provider:
    {{- if eq $sp "onepasswordSDK" }}
    onepasswordSDK:
      vault: {{ .Values.onePassword.vault }}
      auth:
        serviceAccountSecretRef:
          name: {{ .Values.onePassword.accessTokenSecretName }}
          key: {{ .Values.onePassword.accessTokenSecretKey }}
          namespace: {{ .Namespace }}
    {{- else }}
    {{- fail (printf "Unsupported secretProvider: %s" $sp) }}
    {{- end }}
